### ISSUE TITLE
[Feature request] Add arm64 support

### ISSUE THREAD

**Issue by aikooo7** [jlesage/docker-handbrake#366] opened 2024-08-23 12:19 UTC
### Idea

I really like the project, but sadly the image is not arm64, anything I can do to make it work? I don't mind compiling the image myself.

**Comment by aikooo7** [comment] 2024-08-23 12:52
I was able to build the image locally just removing the buildx part, I will keep this open because not everyone might be able to build it locally so I still think an arm64 version of this image should exist

**Comment by jlesage** [comment] 2024-08-23 13:01
Duplicate of https://github.com/jlesage/docker-handbrake/issues/48
The problem is that cross-compiling HandBrake is not easy. HandBrake's build system is not fully adapted for that.

**Closed by jlesage** 2024-08-23 13:01 UTC
Labels: enhancement

**Comment by aikooo7** [comment] 2024-08-23 14:02
> Duplicate of https://github.com/jlesage/docker-handbrake/issues/48
> The problem is that cross-compiling HandBrake is not easy. HandBrake's build system is not fully adapted for that.

You can run the build process that you have right now in an arm64 runner, it should work.

**Comment by jlesage** [comment] 2024-08-23 14:18
I think it would work to make a separate arm64-only image. But I'm not sure how it would work to create a multi-arch image like you can do with buildx.

**Comment by aikooo7** [comment] 2024-08-23 14:25
> I think it would work to make a separate arm64-only image. But I'm not sure how it would work to create a multi-arch image like you can do with buildx.

A separate image is better than none but a multi-arch can be better. If you want to go with the second option why don't you enjoy the beauty of open source and check other projects's github actions and see how they do it?

**Comment by jlesage** [comment] 2024-08-26 23:36
Unfortunately, I didn't find a version of HandBrake being cross-compiled for Linux ARM64.

**Comment by HazMatt69** [comment] 2025-05-05 18:15
Almost a year later and we still can't have an arm64 version? That's too bad...
