### ISSUE TITLE
Failure to initialize Intel Quick Sync Video Starting on v1.22

### ISSUE THREAD

**Issue by noemartinez** [jlesage/docker-handbrake#118] opened 2020-05-08 06:21 UTC
I upgraded to v1.22 and can no longer use Intel QSV. When an encode starts, there's the following error.

```
libva info: VA-API version 1.7.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
[23:06:12] qsv_hevc_make_header: MFXVideoENCODE_EncodeFrameAsync failed (-5)
ERROR: encqsvInit: qsv_hevc_make_header failed
ERROR: Failure to initialise thread 'Quick Sync Video encoder (Intel Media SDK)'
```

Downgrading back to 1.21 with all the same container settings otherwise, fixes the issue.

 I confirmed that ```/dev/dri``` is exposed to the container just fine, so that's not the problem.

Thanks for any help!

**Comment by SemicolonStruggles** [comment] 2020-05-08 19:35
Exact same issue here, with identical logs.

**Comment by jlesage** [comment] 2020-05-19 11:28
Which CPU do you have ? Do you have issue only with H.265? Does H.264 work ?

**Comment by SemicolonStruggles** [comment] 2020-05-19 12:09
My setup is as follows

OS: UnRaid 6.8.3
Docker Version: 19.03.5
CPU: Intel I7-8700

Using QSV:
- Can **NOT** encode to H.265
- Can encode to H.264

Without QSV:
- Can encode to H.265
- Can encode to H.264

**Comment by noemartinez** [comment] 2020-05-19 16:55
My setup is:

OS: Ubuntu 20.04 LTS
Docker Version: 19.03.8
CPU: Intel i5-9600K

I'll try to re-upgrade to 1.22 later today to gather info about the H.265 vs H.64 behavior but I suspect mine will match.

**Comment by J-D-Ball** [comment] 2020-05-21 13:42
Same for me:

OS: UnRaid 6.8.3
Docker Version: 19.03.5
CPU: Intel Xeon E3-1275v5

Using QSV:

    Can NOT encode to H.265
    Can encode to H.264

Without QSV:

   Have not tested but assume working.

**Comment by jlesage** [comment] 2020-05-24 12:44
Looks like its an issue in HandBrake when using the latest Intel Media SDK: https://github.com/HandBrake/HandBrake/issues/2858

**Comment by jlesage** [comment] 2020-05-27 23:21
This should be fixed with the latest image.

**Comment by SemicolonStruggles** [comment] 2020-05-27 23:22
I can confirm it is now working again. Many thanks!

**Closed by jlesage** 2020-05-27 23:21 UTC

**Comment by jlesage** [comment] 2020-05-27 23:23
Great, thanks for confirming!

**Comment by noemartinez** [comment] 2020-05-28 00:30
Fixed for me as well. Thanks for the fix!

**Comment by J-D-Ball** [comment] 2020-05-28 04:39
Fixed for me as well.  Thanks!

**Comment by kuoe0** [comment] 2021-08-10 20:28
Got the same issue on 1.24.

OS: Synology DSM 7
Docker Version: 20.10.3
CPU: Intel J3455

QSV works for H263 but NOT works for H265.

Now, I switched back to use 1.23.2, and QSV works again for H265.

**Comment by Woodflux** [comment] 2022-08-19 08:54
Hi, this issue appears to have returned (or not fixed since last comment).

UnRaid 6.10.3
Intel i5 11400 (using QSV)

Plex & Tdarr can both use QSV to transcode using h265. Handbrake shows h265 capability but fails to encode. H264 works fine. Error message is same as poster above when trying to use h265/qsv:

[12:26:04] Failure to initialise thread 'Quick Sync Video encoder (Intel Media SDK)'

Could be an issue with handbrake itself?
