### ISSUE TITLE
Handbrake not working after OS software upgrade Asustor Lockerstor 2 - Gen 2 

### ISSUE THREAD

**Issue by Doumat** [jlesage/docker-handbrake#285] opened 2023-08-24 18:00 UTC
### Current Behavior

Asustor just upgraded the OS on my Asustor NAS - Lockerstor 2 Gen 2 to 4.2.3.RK91.   The bios is 1.17
Until this upgrade Handbrake was working fine on the NAS , and I accessed Handbrake by clicking the icon in ADM control center, which would open the app.

Now when I click the Handbrake icon,  I get the following message after it fails to connect (see below) 
I have deleted and reinstalled Handbrake but get the same message/issue.  I cannot connect

Thanks, any help is appreciated.

![Screenshot 2023-08-24 134826](https://github.com/jlesage/docker-handbrake/assets/143112228/c4e3d66c-b390-4f07-94da-1e6551c21177)

**Log of the OS upgrade**

![Upgrade ](https://github.com/jlesage/docker-handbrake/assets/143112228/3ee77cb7-752f-48e7-a2ad-750a995adb9b)

### Expected Behavior

Expect the Handbrake app to open

### Steps To Reproduce

not sure.    

### Environment

- OS: Asustor ADM
- OS version: 4.2.3.RK91
- CPU: Intel Celeron
- Docker version:
- Device model: AS6702T-F54F
- Browser/OS: Windows 10  

![Screenshot 2023-08-24 135423](https://github.com/jlesage/docker-handbrake/assets/143112228/8dae3895-7d14-4fae-9f5e-7fb094f60c09)

### Container creation

Just loaded from ADM App Central 

### Container log

```text
?
```

### Container inspect

```text
?
```

**Comment by jlesage** [comment] 2023-08-25 00:06
What URL is used to open the application ?

I never used an Asustor, but can you share any configuration related to the container ?

**Comment by NashRand** [comment] 2023-08-25 15:15
I'm having the same issue on my Asustor NAS.  It was working up until I updated my NAS yesterday.  With the re-install of HB, it is not creating log files under 'Docker/HandBrake/config/log'. I'm just receiving the 'Unable to connect' error when I try the URL localhost:25580.  This worked prior to yesterday's upgrade of the NAS.

**Comment by jlesage** [comment] 2023-08-25 15:20
As mentioned, we need the configuration of the container.  The output of `docker inspect <container name>` would be very useful.

**Comment by jlesage** [comment] 2023-08-25 15:21
Also, I suggest that you seek in parallel support from Asustor, since the issue is most likely coming from the NAS update.

**Comment by NashRand** [comment] 2023-08-25 15:57
Here is the output of docker inspect <container name>.  I've reached out to Asustor but waiting for a response.

[
    {
        "Id": "sha256:48eed0aa73b6be303891cc033a69f46ad2b180ae1f9108d59236b173487dfa28",
        "RepoTags": [
            "jlesage/handbrake:latest"
        ],
        "RepoDigests": [
            "jlesage/handbrake@sha256:5f097b13a5d20efe829204deb8985a6c2b905af1b342a53365bc18e1dcbe465b"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-06-08T14:36:03.3647149Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/base/sbin:/opt/base/bin",
                "ENV=/root/.docker_rc",
                "USER_ID=1000",
                "GROUP_ID=1000",
                "SUP_GROUP_IDS=",
                "UMASK=0022",
                "LANG=en_US.UTF-8",
                "TZ=Etc/UTC",
                "KEEP_APP_RUNNING=0",
                "APP_NICENESS=0",
                "INSTALL_PACKAGES=",
                "CONTAINER_DEBUG=0",
                "DISPLAY_WIDTH=1920",
                "DISPLAY_HEIGHT=1080",
                "DARK_MODE=0",
                "SECURE_CONNECTION=0",
                "SECURE_CONNECTION_VNC_METHOD=SSL",
                "SECURE_CONNECTION_CERTS_CHECK_INTERVAL=60",
                "WEB_LISTENING_PORT=5800",
                "VNC_LISTENING_PORT=5900",
                "VNC_PASSWORD=",
                "ENABLE_CJK_FONT=0",
                "HANDBRAKE_DEBUG=0",
                "HANDBRAKE_GUI=1",
                "AUTOMATED_CONVERSION=1",
                "AUTOMATED_CONVERSION_PRESET=General/Very Fast 1080p30",
                "AUTOMATED_CONVERSION_FORMAT=mp4",
                "AUTOMATED_CONVERSION_SOURCE_STABLE_TIME=5",
                "AUTOMATED_CONVERSION_SOURCE_MIN_DURATION=10",
                "AUTOMATED_CONVERSION_SOURCE_MAIN_TITLE_DETECTION=0",
                "AUTOMATED_CONVERSION_KEEP_SOURCE=1",
                "AUTOMATED_CONVERSION_OUTPUT_DIR=/output",
                "AUTOMATED_CONVERSION_OUTPUT_SUBDIR=",
                "AUTOMATED_CONVERSION_OVERWRITE_OUTPUT=0",
                "AUTOMATED_CONVERSION_VIDEO_FILE_EXTENSIONS=",
                "AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION=ignore",
                "AUTOMATED_CONVERSION_NON_VIDEO_FILE_EXTENSIONS=jpg jpeg bmp png gif txt nfo",
                "AUTOMATED_CONVERSION_MAX_WATCH_FOLDERS=5",
                "AUTOMATED_CONVERSION_CHECK_INTERVAL=5",
                "AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS=",
                "AUTOMATED_CONVERSION_INSTALL_PKGS=",
                "AUTOMATED_CONVERSION_NO_GUI_PROGRESS=0",
                "AUTOMATED_CONVERSION_USE_TRASH=0"
            ],
            "Cmd": [
                "/init"
            ],
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": {
                "/config": {},
                "/output": {},
                "/storage": {},
                "/trash": {},
                "/watch": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.description": "Docker container for HandBrake",
                "org.label-schema.name": "handbrake",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-handbrake",
                "org.label-schema.version": "23.06.1"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 335573621,
        "VirtualSize": 335573621,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/af908d775a686fd555c53493929415316f44c6c03399871d6d3884dec77a1a58/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/f88dc6ad579a7caf3d61148fa3606125e22349687a37c87efa82dd1dc2038583/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/f6b280df8fdc3a17ea82aa83e7c9efad14808a6d68424745f2586d3d65680ea8/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/d3ce17d3b0d41d7de7e6fec0a8302fc82a1be93418caf979eca79940ed7d1b52/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/4198a8ea7253a0a1d7e2155e5725f4b13e9b68c3eb8b2267b17298caab0ec1d6/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/b1495dba1e762b40b1f1d4dd9a46b92bff00c0035cc67c03f7423fbc86ccab1f/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/2981a00d920f72cdfd4f95e4ef3a94f9547c293026d76d38da21538a73ff2a0b/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/72e24f8092f1ff056d205fe3e3e65ed0cba8f65aa10d15bc78320f898705bbb8/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/6d2a5c6a022edc4b58c9e0b5839aeafff8af8d036ba495adf7445f051d44101b/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/b79ca28580bd255786df8fbc9fe0441aa55b71da9b6d4d5b12a0475a6415459f/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/c3eaf5d2b649b2f2581997067d469d396033db0fcbe0251fe0ffdc965fe2f381/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/8efb99d770e70f420e5f1008a355cfae9020eef9c9da8ce1f844375e9ca71080/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/c38f4547faaf4e3da447b52851993ea24d9642383fffd2aadee4cd89aece80d4/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/b83ef6603582bbc806b44a0a14d7993ec898057805a97d98b42ab89ed382dda7/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/e08c4933619db9a9a8c042a5fd7208ab1c4e903369e06d5c4735ee1e89791bc2/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/aef40fd8951653622f4717af145fcae639aae024be24dd173f92652fdeef31f6/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/ac97f881e74c08aa4fe7796c282c42e60dde8f480d797c8b14eff3da18cd824a/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/f7a945dad4e48374b3ce19ac128007899c0761274a804a2866473227cbb34292/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/6e901f6789b4029b09f5b46be41db682204a7f225c5c5bdcd23daf550b3b24f0/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/9b450fdea18a8e7cd16d651152125022366be6dfb2e7fb9b19f633779122a339/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/574e00e95bb17c3796db6b2115feb2589b6e695aad243d56775d80084cf57357/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/2e3bc5a1d36b5b8cf87adad202f0e445f48b364f663199152c6c0e9dc71cdd24/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/459ea9c9f137822661281b6ed4c109756b869a997ca3233b2d32475541277db4/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/ea8e93b26827b44a728d1af961a512bafceb3edd8bc2f61c921bdb63736c1211/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/eaea5f9f050eaa42ab5f3042522d3de353bbffdcee112dabad25146bf52569f7/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/df72ededfe7eefa1671226ae8fbf7adad16f965b3c3c0bafc25aeda4b3b2be7f/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/dc9936e6aec342d08dd3944cb81292aea70ae4e81a0a7be43bb34be149f374f2/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/c27690a6e1b86f2299d123960d5ce9e1bfac4293cae193e0710f8df50c77b9f3/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/c9310616e3963daef641f2761c464eb6a9a7ff73606c8b9ff8a7b9acd1f0ea33/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/da68f0486f5770099648763c893ebc73fa273e472bb776b50f16b48712d5d7d9/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/dae6653b6193a9835717575e4e945133138cc5543253f93b97e1b8f128a1190d/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/3d1a33173c58354642ac68068769116b2a9ea202b65c9a802ab9bbce8d5bce01/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/2d02629cedfe4ed2899154f68d37fdbd1b63630bc4d89079943eeaa35dd89cad/diff",
                "MergedDir": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/c336087102b20bd11333c49b69322110517662134ddf94c3e8d9b3122676dafe/merged",
                "UpperDir": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/c336087102b20bd11333c49b69322110517662134ddf94c3e8d9b3122676dafe/diff",
                "WorkDir": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/c336087102b20bd11333c49b69322110517662134ddf94c3e8d9b3122676dafe/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:f1417ff83b319fbdae6dd9cd6d8c9c88002dcd75ecf6ec201c8c6894681cf2b5",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:eceb58ccfea64887bce474c24959669b8c2ae838f0416baff512602fb6eec4f1",
                "sha256:0d174ad44f4de589ba7f098fda8fca5623f59bbd32654b49f8dded47eceec412",
                "sha256:067a9932096f950ed2a08346131b6a353f032cc5e23a7da14ef4b7ac6654e08c",
                "sha256:8ea7f27d0122dd11ff978fa3f0cef0f0ffa6ae20f2fd3f6e16c4555428700664",
                "sha256:c15149c830dcd67f82fce844489eb01a960fc9db8e9115e31ed7e9b0a732000b",
                "sha256:edcad89fd4bf6ccf8ec6a4e814998ada49740216473a87454255e512fc0f6c6f",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:da897b33ba3e2723cbc7f50251bee765e3115cbd36d7ce4f8fec05133c69901b",
                "sha256:7c3bfa0b3e037f0bf0906007f90f67cbd402e9c5f30fcd4886997ca475fdafb1",
                "sha256:bd06e15643544470ee541bcb744fa14375d344239df106c721b92b9787b83d9f",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:3a98d59647a6679b67d764273f02a531f03297676b367b746bf78c5af516d1ca",
                "sha256:115b37ee7245be2dd0f43d1966383347a42c4ad80d4ff663e632d53318bff16b",
                "sha256:cb415dd3806e31eeaf5192ee695c66f7e47b3a539cc0726070816d5a80af5418",
                "sha256:660b9889304123d27d92d3c012e970d02edc1c8b67da134398d2c077384f265c",
                "sha256:377d0856a5b617def26bf87c59c5d95f1a9b1d11c735655ebd587d224fe4cef4",
                "sha256:45fdf421e880827e46422d1f9a56661fd5f2def613ab6097396edcf64ac57235",
                "sha256:8be727cd2aeb04c3bf1c1007be2f29cbeedb3def6d0b9a8459598caf82d19e19",
                "sha256:2bff565a5dd90e434fe796b7c1408c6b1fcf70136a3b33138fb8bef2f5f19fe2",
                "sha256:44e6317406f935b6d0ef105db9e90677961eaf8bb17f64c2cfa42de1beab34ea",
                "sha256:a50529b6b6c086130f5e955342f2fabe3d785972a80852fb4e9a7c56f75ee6d8",
                "sha256:bd66dfc61422beb6951025cd2ce4a55b8131bca3f3dc827ac7ad41debf146955",
                "sha256:c15ef9fae24b93d667043c04a92b7d78200af838ce416e173c82754336f62608",
                "sha256:bb103f21a1eab17c5db3685162f78541b8006f28854e5c62c51b31382933db3e",
                "sha256:5cb82fe6efa11998a2f5e2b2d53b17a198714fd749041c80d4d0a82f6653b31c",
                "sha256:1ba457db78e2de0b9869e329e3aa6e3c6875d6f01ab5027673d9ea37a371d3e3",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:f5016425c51ccb8d059d92805f64521d2219c12f4bd1a751bb48664ef1df142c",
                "sha256:34a2b5f4bcc69ef392d33772f6485b019ded1df801a9b8ddebc733b1f0e1bfa9",
                "sha256:9d94eda7838a385f0cb05545f9723eca39ebe2e0aa961fdcaa29f92c6b28a110",
                "sha256:dcd93f623d5ff369344d04f5e5f67ac5bd4cadad9df43264bda04d90d4e9477d",
                "sha256:37b3ebdbaf3712d7d2ea9350fe56bd31a0a194bc7b9f7250acfdc8e0e6a01d67"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**Comment by jlesage** [comment] 2023-08-25 22:52
Did you run `docker inspect` on a running container ?  Looks like it has been executed on an image.

**Comment by NashRand** [comment] 2023-08-26 00:35
If I remember correctly, they just need to be turned on, which they are.  (see pic).  Is there anything else I should be looking for?
![image_2023-08-25_193545378](https://github.com/jlesage/docker-handbrake/assets/48554321/f2d12477-320e-4bb7-87f9-cafde8a60391)

**Comment by Doumat** [comment] 2023-08-26 21:25
Sorry  I'm new to the NAS world, so see so don't know hot t access docker inspect but if you can let me know, I will provide what I can.

**Comment by NashRand** [comment] 2023-08-27 01:06
You need to ssh into the NAS via PuTTy for Windows or Terminal for Mac.  I don't believe there is a way to run commands directly from an Asustor NAS.

**Comment by NashRand** [comment] 2023-08-30 19:22
There is a Handbrake update in Asustor App Central that fixes this.  A msg from Patrick: "Did you also update ADM to ADM 4.2.3.RK91 ?
If yes, this is the major problem to cause the HandBrake not working.
It's related to the hardware transcoding feature enabled in HandBrake, and the permission to access this feature on the NAS is changed from ADM 4.2.3.  I've update the configuration of HandBrake to fullfill the permission requirement to use the hardware transcoding, and the updated version is released to App Central."

**Comment by jlesage** [comment] 2023-08-30 20:31
Thanks for the update.  I think we can close this issue.

**Closed** 2023-08-30 20:31 UTC
Labels: bug

**Comment by Doumat** [comment] 2023-08-31 01:18
Thank you !
