### ISSUE TITLE
How to determine why Automatic Conversion not working

### ISSUE THREAD

**Issue by gabs247** [jlesage/docker-handbrake#17] opened 2018-05-04 11:27 UTC
Your container is great, I've done the manual conversion and it works so well!

However, I'm not sure if I've missed a prerequisite or config'd something incorrectly, but the Automatic Conversion doesn't seem to be working. I've read the Readme a few times, and it seems quite straightforward, but when I put a Movie with a VIDEO_TS folder into the watch folder, nothing seems to happen. Should I see it in the Queue or Activity Log? Are there any logs or anything that I can look up to see what could be happening?

Any advice would be much appreciated, I'd really like to automatically convert my DVD backups, but I'd be still happy to do them manually if I can't get this working so really happy for your efforts 👍

**Comment by jlesage** [comment] 2018-05-04 12:46
Since it's separate feature, the automatic video conversion status is not visible through the GUI.  You have to looks the container's log.  You can do it via the following command:
```
docker logs <container name>
```

**Comment by gabs247** [comment] 2018-05-05 10:31
Thanks for the response, yes, I can now see why nothing is happening. When the VIDEO_TS folders are found, the processing starts, but for some reason the log indicates:
`[autovideoconverter] 0 title(s) to process.`
Any idea why this might be happening? When I open the folder manually, it finds the titles and allows me to manually convert them.

**Comment by jlesage** [comment] 2018-05-05 11:58
What’s the length of the titles when you open it manually?  Maybe they are shorter than `AUTOMATED_CONVERSION_SOURCE_MIN_DURATIONˋ?

**Comment by gabs247** [comment] 2018-05-05 22:56
They are movies, so greater than an hour. I tried setting the duration to 1, but still nothing. I also reset the Automatic env variables to default, but still not converting. I had some metadata in one of the folders, and they were converted to an mkv for some reason, but the VIDEO_TS was skipped :(
So my watched folder has a `watch\[MOVIE]\VIDEO_TS` format, where VIDEO_TS contains all the BUP/IFO/VOB files in it...I'm not sure what else could be going wrong here.

**Comment by jlesage** [comment] 2018-05-07 00:40
I tried to reproduce and I see that the handbrake cli is crashing (you should see "Segmentation fault" in the log.
Look like an old crash that is coming back.  I will investigate this...

**Comment by jlesage** [comment] 2018-05-09 15:55
Crash fixed in version 1.13.2.

**Closed by jlesage** 2018-05-09 15:55 UTC
