### ISSUE TITLE
Permission Errors With Newly Created Container

### ISSUE THREAD

**Issue by BzowK** [jlesage/docker-handbrake#18] opened 2018-05-08 17:19 UTC
Hey Guys - 

I'm having an issue starting this container after trying multiple configurations so thought I'd post.  After building and starting the container, it stops on it's own.  Checking the logs, I get:

> [cont-init.d] 00-take-config-ownership.sh: ERROR: Failed to take ownership and no write permission on /config.,
> chown: /config: Permission denied

Below is the string I most recently used to try to install it:

> docker run -d \
>     --name=handbrake \
>     -p 5800:5800 \
>     -e PGID=0 -e PUID=0 \
>     -v ~/handbrake/config:/config:rw \
>     -v ~/handbrake:/storage:ro \
>     -v ~/handbrake/watch:/watch:rw \
>     -v ~/handbrake/output:/output:rw \
>     jlesage/handbrake
> 

Below is what I've tried to resolve it:
- Verifying permissions on ~/handbrake/config - they are set to 0777
- Deleting container + volumes and reinstalling it - multiple times
- Adding the line -e PGID=0 -e PUID=0 \shown above (had same error when it's not included and know IDs are 0
- Attempting to use the "quick start" string on the page.  When using my string above in SSH, it executes fine.  When using the quick start one, it fails stating "/usr/bin/docker-current: Error response from daemon: error while creating mount source path '/docker/appdata/handbrake': mkdir /docker: operation not permitted."
- Trying to add config volume is various locations - the string creates the paths successfully, but still get error

I'm running Docker on a Project Atomic (Fedora) host.  Other containers I have on it work fine. including Portainer, a mySQL DB, etc.  I'm running strings from an SSH session logged in as root.  The full log is below:

> [s6-finish] sending all processes the KILL signal and exiting.,
> [s6-finish] sending all processes the TERM signal.,
> [s6-finish] syncing disks.,
> [cont-finish.d] done.,
> [cont-finish.d] executing container finish scripts...,
> [services.d] stopping s6-fdholderd...,
> [services.d] stopping services,
> [cont-init.d] 00-take-config-ownership.sh: exited 1.,
> [cont-init.d] 00-take-config-ownership.sh: ERROR: Failed to take ownership and no write permission on /config.,
> chown: /config: Permission denied,
> [cont-init.d] 00-take-config-ownership.sh: executing... ,
> [cont-init.d] 00-set-home.sh: exited 0.,
> [cont-init.d] 00-set-home.sh: executing... ,
> [cont-init.d] 00-set-app-deps.sh: exited 0.,
> [cont-init.d] 00-set-app-deps.sh: executing... ,
> [cont-init.d] 00-clean-tmp-dir.sh: exited 0.,
> [cont-init.d] 00-clean-tmp-dir.sh: executing... ,
> [cont-init.d] 00-clean-logmonitor-states.sh: exited 0.,
> [cont-init.d] 00-clean-logmonitor-states.sh: executing... ,
> [cont-init.d] 00-app-user-map.sh: exited 0.,
> [cont-init.d] 00-app-user-map.sh: executing... ,
> [cont-init.d] 00-app-script.sh: exited 0.,
> [cont-init.d] 00-app-script.sh: executing... ,
> [cont-init.d] 00-app-niceness.sh: exited 0.,
> [cont-init.d] 00-app-niceness.sh: executing... ,
> [cont-init.d] executing container initialization scripts...,
> [fix-attrs.d] done.,
> [fix-attrs.d] applying ownership & permissions fixes...,
> [s6-init] ensuring user provided files have correct perms...exited 0.,
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.,[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

Any suggestions?  Thanks!

**Comment by jlesage** [comment] 2018-05-08 22:26
What is the user and group of your config folder on the host?
Also, to set the user/group under which handbrake runs, you need to set USER_ID and GROUP_ID (not PGID/PUID).

**Comment by BzowK** [comment] 2018-05-09 19:54
Thanks for the reply...

After reading your reply, I looked back at the variables you listed and added a couple so that I ran the container using the modified string below.  I got a little further, but still having similar issue.  

> docker run -d \
> --name=handbrake \
> -p 5800:5800 \
> -e USER_ID=0 \
> -e GROUP_ID=0 \
> -v ~/handbrake/config:/config:rw \
> -v ~/handbrake:/storage:ro \
> -v ~/handbrake/watch:/watch:rw \
> -v ~/handbrake/output:/output:rw \
> jlesage/handbrake

Once complete, I couldn't access the webui, so looked at the logs and this time have something slightly different...
> mkdir: can't create directory '/config/log/': Permission denied,
> [s6-finish] sending all processes the KILL signal and exiting.,
> [s6-finish] syncing disks.,
> [s6-finish] sending all processes the TERM signal.,
> [cont-finish.d] done.,
> [cont-finish.d] executing container finish scripts...,
> [services.d] stopping s6-fdholderd...,
> [services.d] stopping services,
> [cont-init.d] 10-nginx.sh: exited 1.,
> [cont-init.d] 10-nginx.sh: executing... ,
> [cont-init.d] 10-cjk-font.sh: exited 0.,
> [cont-init.d] 10-cjk-font.sh: executing... ,
> [cont-init.d] 10-certs.sh: exited 0.,
> [cont-init.d] 10-certs.sh: executing... ,
> [cont-init.d] 00-take-config-ownership.sh: exited 0.,
> chown: /config: Permission denied,
> [cont-init.d] 00-take-config-ownership.sh: executing... ,
> [cont-init.d] 00-set-home.sh: exited 0.,
> [cont-init.d] 00-set-home.sh: executing... ,
> [cont-init.d] 00-set-app-deps.sh: exited 0.,
> [cont-init.d] 00-set-app-deps.sh: executing... ,
> [cont-init.d] 00-clean-tmp-dir.sh: exited 0.,
> [cont-init.d] 00-clean-tmp-dir.sh: executing... ,
> [cont-init.d] 00-clean-logmonitor-states.sh: exited 0.,
> [cont-init.d] 00-clean-logmonitor-states.sh: executing... ,
> [cont-init.d] 00-app-user-map.sh: exited 0.,
> [cont-init.d] 00-app-user-map.sh: executing... ,
> [cont-init.d] 00-app-script.sh: exited 0.,
> [cont-init.d] 00-app-script.sh: executing... ,
> [cont-init.d] 00-app-niceness.sh: exited 0.,
> [cont-init.d] 00-app-niceness.sh: executing... ,
> [cont-init.d] executing container initialization scripts...,
> [fix-attrs.d] done.,
> [fix-attrs.d] applying ownership & permissions fixes...,
> [s6-init] ensuring user provided files have correct perms...exited 0.,[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

Seemingly it's still trying to execute chown against /config and is failing which causes the whole thing to stop when it cannot create the log folder within the path.  I looked at the config folder (which was obviously created automatically when running the above) and it has the User and Group set to "root" with permissions level of 0755.  I tried changing permissions to 0777 recursively then starting the container again, but got the same results.  

What I don't understand is if I'm executing the string as root and defining both IDs as 0, why it still fails.  How should the config folder be configured?  I did verify that "0" is correct for both - below is the output from "id root""

> uid=0(root) gid=0(root) groups=0(root)

Thanks again!

**Comment by jlesage** [comment] 2018-05-10 09:43
If you don't set volume mappings, does it work?
```
docker run -p 5800:5800 jlesage/handbrake
```

**Comment by jlesage** [comment] 2019-09-03 01:49
Closing this issue.  Please re-open if needed.

**Closed by jlesage** 2019-09-03 01:49 UTC

**Comment by MacGyver27** [comment] 2021-03-22 19:05
Hi,

Using latest image and getting similar error messages in `conversion.log` file:

```
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
```

Any idea what it might be? thanks

**Comment by hardwareadictos** [comment] 2022-05-31 11:39
> Hi,
> 
> Using latest image and getting similar error messages in `conversion.log` file:
> 
> ```
> set_mempolicy: Operation not permitted
> set_mempolicy: Operation not permitted
> set_mempolicy: Operation not permitted
> set_mempolicy: Operation not permitted
> set_mempolicy: Operation not permitted
> set_mempolicy: Operation not permitted
> set_mempolicy: Operation not permitted
> set_mempolicy: Operation not permitted
> set_mempolicy: Operation not permitted
> set_mempolicy: Operation not permitted
> set_mempolicy: Operation not permitted
> ```
> 
> Any idea what it might be? thanks

Having this issue also, not allowing me to transcode

**Comment by hardwareadictos** [comment] 2022-06-25 09:30
No one?

**Comment by jlesage** [comment] 2022-06-26 16:04
Can you share the full log ?  Are these messages the cause of the conversion failure ?
