### ISSUE TITLE
 no sound after transcoding

### ISSUE THREAD

**Issue by link1254** [jlesage/docker-handbrake#117] opened 2020-05-06 08:02 UTC
Hello,
 I just installed handbrake on my nas to be able to transcode video in h264 and AAC so that they are better readable from plex. I imported my transcoding preset that I had created on the pc version of handbrake but when I transcode a video from my nas that if is without sound while in my preset I will ask handbrake to take all audio pist who are French, English and Japanese.
I realized that if I want to have sound on my videos, I have to add the audio tracks manually.
how to make handbrake on my nas react like on my pc and detect all audio tracks of a video file by itself

here my presets
[HANBRASKE PREST.txt](https://github.com/jlesage/docker-handbrake/files/4585471/HANBRASKE.PREST.txt)

**Comment by jlesage** [comment] 2020-05-08 20:47
How your audio track selection settings look like in the UI ?

**Comment by link1254** [comment] 2020-05-09 20:59
![image](https://user-images.githubusercontent.com/63971266/81484730-55065380-9248-11ea-8642-6df76fc0e458.png)

my preset work on my PC and not on my nas. should i change something

**Comment by jlesage** [comment] 2020-05-09 22:52
Maybe the issue is that you don't have any audio encoder.  Try to add the AAC encoder (the same as your Passthru Fallback).

**Comment by jlesage** [comment] 2023-11-16 18:28
Closing this issue.  Please re-open if needed.

**Closed by jlesage** 2023-11-16 18:28 UTC
