### ISSUE TITLE
AUTOMATED_CONVERSION_PRESET no longer recognized

### ISSUE THREAD

**Issue by eng3** [jlesage/docker-handbrake#116] opened 2020-05-05 03:35 UTC
AUTOMATED_CONVERSION_PRESET is no longer recognizing my custom preset.  Log states "Invalid Preset" even though it is listed in the proceeding list of presets.  Exact same configuration works when reverting back to v1.21.0

**Comment by monkeyhat** [comment] 2020-05-05 12:13
I'm seeing this too.  

On my install, after I'd set up the four presets I wanted to use for automated conversions, I removed all the rest from the presets.json file.  Since yesterday's update, when Handbrake tries an automated encode, the log states "Invalid preset" followed by the name of my custom preset - then says "Valid presets are:" and lists all the original default presets (which are no longer in my presets.json file) followed by my four custom presets.  

If I change my AUTOMATED_CONVERSION_PRESET variable to be one of the original default presets (as listed in the log) and restart the container - encodes still fail with "Invalid preset"

If I go into Handbrake via the web interface, I only see my custom presets and none of the original defaults mentioned in the log.  

If I then use the web interface to manually convert a video from the "watch" folder using the same preset specified in AUTOMATED_CONVERSION_PRESET, it works fine.  

Hope that helps narrow it down!

**Comment by jlesage** [comment] 2020-05-05 23:49
It seems that some changes happened in the latest HandBrake version about how a preset is identified.

Try to set the folder/group under which your preset appears in the UI.  For example, if your preset `MyCustomPreset` appears under `My General`, set `AUTOMATED_CONVERSION_PRESET ` to `My General/MyCustomPreset`.

**Comment by Jtomage** [comment] 2020-05-06 02:26
Got the official preset working. Set

`AUTOMATED_CONVERSION_PRESET=General/{Official Preset}`

**Comment by mikepauer** [comment] 2020-05-06 20:33
Was also seeing this, can confirm I had to set `AUTOMATED_CONVERSION_PRESET=Matroska/myh265` instead of the old `AUTOMATED_CONVERSION_PRESET=myh265` for it to start working again.

**Comment by matze0301** [comment] 2020-05-07 20:53
I can confirm the problem and the solution, except that i didn't see "invalid preset" in "docker logs handbrake", just a fail to convert.

Image 1.22.0

**Comment by eng3** [comment] 2020-05-07 20:59
The error shows up in the conversion log.  Anyways, I can confirm the solution as well.  It would be nice if this change were documented somewhere like the change log perhaps

**Comment by cjchiarello** [comment] 2020-05-08 12:37
how do i fix this from bash? 
i never setup a custom conversion preset, I have always just dropped files in the /watch folder and waited for them to finish as an mp4 in /output

**Comment by SemicolonStruggles** [comment] 2020-05-08 20:02
I have a custom preset called `H.265 MKV 1080 Audio Passthrough` listed under `Custom/Matroska`

Prefixing the `AUTOMATED_CONVERSION_PRESET` with 'Matroska/' did not work for me.

I checked my conversion.log and found that the Matroska category was listed multiple times under valid presets.

I fixed the issue by saving my preset to a new category called 'Personal' and set the `AUTOMATED_CONVERSION_PRESET` to `Personal/H.265 MKV 1080 Audio Passthrough`

[conversion.log](https://pastebin.com/raw/9Sa6KjcS)

**Comment by jlesage** [comment] 2020-05-08 20:42
> how do i fix this from bash?
> i never setup a custom conversion preset, I have always just dropped files in the /watch folder and waited for them to finish as an mp4 in /output

Are you saying that you were using the default preset ?  I will push an update to fix the default preset as well.

**Comment by cjchiarello** [comment] 2020-05-09 03:26
> > how do i fix this from bash?
> > i never setup a custom conversion preset, I have always just dropped files in the /watch folder and waited for them to finish as an mp4 in /output
> 
> Are you saying that you were using the default preset ? I will push an update to fix the default preset as well.

yes i was just running the default preset - I haven't taken the time to look into having a custom preset run automatically

**Comment by SemicolonStruggles** [comment] 2020-05-10 08:47
> yes i was just running the default preset - I haven't taken the time to look into having a custom preset run automatically

Issues with the default preset should be fixed in a145219, try updating your container.

**Comment by jlesage** [comment] 2021-01-01 18:25
Closing issue.  Please re-open if there is still a problem.

**Closed by jlesage** 2021-01-01 18:25 UTC
